api:
  key: '{cipher}5d0d1542c2a32af3035f8a156f607fcc328828881eb580cba2c4408495ec1882a08ab733334a6c514dee39d5125b1ca6a12818bdba780b4d1d690cf05f4356c3'
  url: '{cipher}3900edbbe87293d866e69655c2f0bac81d22597722402b2b107f65b76b417419d103852368fe25a5710f6643c2dea66e3873b6d4531902720b09157d7ca0093ea62978a114788130b0566f31356202bd'
  #url: "https://api.apilayer.com/exchangerates_data/convert"
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5555/currency
    username: postgres
    password: '{cipher}8d462f37e750531a933d7357243683b22d63e9262a250ff1f5de58fbda2fb930'

  config:
    import: optional:file:.env[.properties]
  application:
    name: currencykotlin
  jpa:
    hibernate:
      ddl-auto: update

  
server:
  port: 7778

keycloak:
  config:
    import: optional:file:.env[.properties]
  realm: testing2
  auth-server-url: ${URL_KEYCLOAK}
  autodetect-bearer-only: true
  ssl-required: none
  resource: backend
  credentials:
    secret: J82JDRDUaIyMABThMlFGvQid1jsULeG5
  use-resource-role-mappings: false
  security-constraints:
    - auth-roles:
        - ADMIN
      security-collections:
        - name: SERVICIOS DEL ADMINISTRADOR
          methods:
            - GET
          patterns:
            - /api/v1/currency/all
    - auth-roles:
        - USER
      security-collections:
        - name: SERVICIOS DEL USUARIO
          methods:
            - GET
          patterns:
            - /api/v1/currency/convert
